name: Catalog Hub

on:
  push:
    paths:
      - catalog-hub/**
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:

      working-directory: ./catalog-hub

    defaults:
      run:
        working-directory: ${{ env.working-directory }}

    steps:

      - uses: actions/checkout@v4


      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'
      - name: Grant execute permission for Maven Wrapper
        run: chmod +x mvnw  # Fixes possible permission issues

      - name: Build with Maven
        run: ./mvnw -ntp verify # compile and verify your Spring Boot app